In [2]:
import numpy as np
import dedalus.public as d3
import matplotlib.pyplot as plt

Nphi = 512
Nr = 256
mmax = (Nphi - 1) // 2
dtype = np.float64
dealias = 3/2

coords = d3.PolarCoordinates('phi', 'r')
dist = d3.Distributor(coords, dtype=dtype)
disk = d3.DiskBasis(coords, shape=(Nphi, Nr), radius=1, dealias=dealias, dtype=dtype)
edge = disk.edge
radial_basis = disk.radial_basis
phi, r = dist.local_grids(disk, scales=(1, 1)) 
phi_deal, r_deal = dist.local_grids(disk, scales=(dealias, dealias))

In [3]:
phi_deal

array([[0.        ],
       [0.00818123],
       [0.01636246],
       [0.02454369],
       [0.03272492],
       [0.04090615],
       [0.04908739],
       [0.05726862],
       [0.06544985],
       [0.07363108],
       [0.08181231],
       [0.08999354],
       [0.09817477],
       [0.106356  ],
       [0.11453723],
       [0.12271846],
       [0.13089969],
       [0.13908092],
       [0.14726216],
       [0.15544339],
       [0.16362462],
       [0.17180585],
       [0.17998708],
       [0.18816831],
       [0.19634954],
       [0.20453077],
       [0.212712  ],
       [0.22089323],
       [0.22907446],
       [0.2372557 ],
       [0.24543693],
       [0.25361816],
       [0.26179939],
       [0.26998062],
       [0.27816185],
       [0.28634308],
       [0.29452431],
       [0.30270554],
       [0.31088677],
       [0.319068  ],
       [0.32724923],
       [0.33543047],
       [0.3436117 ],
       [0.35179293],
       [0.35997416],
       [0.36815539],
       [0.37633662],
       [0.384

In [2]:
r_deal

array([[0.00312721, 0.00717819, 0.01125298, 0.01533299, 0.01941479,
        0.02349726, 0.0275799 , 0.03166241, 0.03574462, 0.03982639,
        0.04390761, 0.04798818, 0.05206801, 0.05614702, 0.06022514,
        0.06430228, 0.06837838, 0.07245336, 0.07652714, 0.08059967,
        0.08467086, 0.08874066, 0.09280898, 0.09687576, 0.10094093,
        0.10500443, 0.10906617, 0.11312611, 0.11718416, 0.12124026,
        0.12529434, 0.12934633, 0.13339616, 0.13744378, 0.1414891 ,
        0.14553206, 0.1495726 , 0.15361064, 0.15764612, 0.16167897,
        0.16570913, 0.16973652, 0.17376108, 0.17778274, 0.18180143,
        0.18581709, 0.18982965, 0.19383905, 0.19784521, 0.20184807,
        0.20584756, 0.20984361, 0.21383617, 0.21782516, 0.22181051,
        0.22579216, 0.22977004, 0.23374409, 0.23771424, 0.24168042,
        0.24564257, 0.24960062, 0.2535545 , 0.25750415, 0.26144951,
        0.2653905 , 0.26932706, 0.27325913, 0.27718664, 0.28110952,
        0.28502772, 0.28894115, 0.29284976, 0.29

In [3]:
import scipy as sp

In [4]:
k = 0
m = 0
zs, _ = sp.special.roots_jacobi(int(3*Nr/2), k, m)
roots = np.sqrt((zs + 1)/2)#2*zs**2 - 1

In [5]:
roots

array([0.00312721, 0.00717819, 0.01125298, 0.01533299, 0.01941479,
       0.02349726, 0.0275799 , 0.03166241, 0.03574462, 0.03982639,
       0.04390761, 0.04798818, 0.05206801, 0.05614702, 0.06022514,
       0.06430228, 0.06837838, 0.07245336, 0.07652714, 0.08059967,
       0.08467086, 0.08874066, 0.09280898, 0.09687576, 0.10094093,
       0.10500443, 0.10906617, 0.11312611, 0.11718416, 0.12124026,
       0.12529434, 0.12934633, 0.13339616, 0.13744378, 0.1414891 ,
       0.14553206, 0.1495726 , 0.15361064, 0.15764612, 0.16167897,
       0.16570913, 0.16973652, 0.17376108, 0.17778274, 0.18180143,
       0.18581709, 0.18982965, 0.19383905, 0.19784521, 0.20184807,
       0.20584756, 0.20984361, 0.21383617, 0.21782516, 0.22181051,
       0.22579216, 0.22977004, 0.23374409, 0.23771424, 0.24168042,
       0.24564257, 0.24960062, 0.2535545 , 0.25750415, 0.26144951,
       0.2653905 , 0.26932706, 0.27325913, 0.27718664, 0.28110952,
       0.28502772, 0.28894115, 0.29284976, 0.29675349, 0.30065

In [6]:
np.gradient(roots)

array([4.05098594e-03, 4.06288808e-03, 4.07739916e-03, 4.08090544e-03,
       4.08213697e-03, 4.08255238e-03, 4.08257404e-03, 4.08236259e-03,
       4.08199034e-03, 4.08149384e-03, 4.08089323e-03, 4.08020036e-03,
       4.07942257e-03, 4.07856463e-03, 4.07762972e-03, 4.07662006e-03,
       4.07553723e-03, 4.07438237e-03, 4.07315634e-03, 4.07185978e-03,
       4.07049320e-03, 4.06905699e-03, 4.06755146e-03, 4.06597688e-03,
       4.06433346e-03, 4.06262137e-03, 4.06084076e-03, 4.05899177e-03,
       4.05707450e-03, 4.05508907e-03, 4.05303556e-03, 4.05091406e-03,
       4.04872464e-03, 4.04646738e-03, 4.04414235e-03, 4.04174960e-03,
       4.03928921e-03, 4.03676123e-03, 4.03416573e-03, 4.03150275e-03,
       4.02877237e-03, 4.02597464e-03, 4.02310961e-03, 4.02017735e-03,
       4.01717790e-03, 4.01411133e-03, 4.01097770e-03, 4.00777705e-03,
       4.00450946e-03, 4.00117498e-03, 3.99777367e-03, 3.99430560e-03,
       3.99077081e-03, 3.98716938e-03, 3.98350137e-03, 3.97976684e-03,
      

In [7]:
np.min(np.gradient(roots))

np.float64(2.087382862236975e-05)

In [13]:
0.25 * np.min(np.gradient(roots)) / 100

np.float64(5.218457155592437e-08)

I mean, sure, maybe 5e-8 still isn't small enough for stability (in the worst case scenario)? 
... 
we could try 1e-8... or even smaller...? 